### ISSUE TITLE
Author checksum showing on the front end

### ISSUE THREAD

**Issue by cyphun** [uoregon-libraries/sb-dspace7-rest#24]
Reproduction steps:

1. Viist https://scholarsbank.uoregon.edu/search?spc.page=1&query=harbeson
2. Observe the top result

![Image](https://github.com/user-attachments/assets/a6099879-8a0d-476d-a721-9874d66466cd)

### Acceptance criteria
- [ ] Ensure the author names are displaying without the checksums

**Comment by john-zhang1** [comment]
There is an issue with the entry. The name might be in a specific format when entered. Remove any formatting and set the language to English, and the error is gone in my screen.

**Comment by cyphun** [comment]
@caflynn - can you verify that this looks good?

**Comment by caflynn** [comment]
It does now appear correctly on the page, thank you.

**Comment by cyphun** [comment]
Thanks, closing this issue.
